package com.agentmemory.curate;

import com.agentmemory.core.Identity;
import com.agentmemory.core.PagePath;
import com.agentmemory.links.WikiLinkService;
import com.agentmemory.recall.Scope;
import com.agentmemory.store.PageRecord;
import com.agentmemory.store.PageRepository;
import com.agentmemory.wiki.WikiWriter;
import java.util.List;

/**
 * {@code memory_lint} (issue #29): the curator's zero-cost rule findings plus an optional LLM
 * contradiction pass, optionally persisted as a {@code _lint/} page.
 *
 * <p>This is the single surface that covers the issue's "curator" and "memory_lint" items via flags:
 * <ul>
 *   <li><strong>report-only</strong> — {@code dryRun = true} computes the findings and writes nothing.</li>
 *   <li><strong>stage</strong> — {@code dryRun = false} persists the report under {@code _lint/}.</li>
 *   <li><strong>rules only / + contradictions</strong> — {@code includeContradictions} toggles the
 *       (paid) LLM pass; with it off, a run is purely the zero-cost curator.</li>
 * </ul>
 *
 * <p>The persisted page is written through the same atomic row + wiki-file + commit path consolidation
 * uses ({@link PageRepository#create} with a {@link WikiWriter} callback) and its {@code [[links]]} to
 * the flagged pages are maintained by {@link WikiLinkService#syncPageLinks} (#27), so the lint report is
 * itself a first-class, navigable node in the graph. The contradiction pass audits only real knowledge
 * pages — control pages ({@code _rules/}, {@code _slots/}, {@code _lint/}) are excluded so the report
 * never audits itself.
 */
public class MemoryLintService {

    /** The single, latest-versioned lint page per project (re-consolidated on each staged run). */
    public static final String LINT_PATH = "_lint/report.md";

    private static final String LINT_TITLE = "Lint report";

    private final CuratorService curator;
    private final ContradictionDetector detector;
    private final PageRepository pages;
    private final WikiWriter wikiWriter;
    private final WikiLinkService links;

    public MemoryLintService(
            CuratorService curator,
            ContradictionDetector detector,
            PageRepository pages,
            WikiWriter wikiWriter,
            WikiLinkService links) {
        this.curator = curator;
        this.detector = detector;
        this.pages = pages;
        this.wikiWriter = wikiWriter;
        this.links = links;
    }

    /**
     * Run a lint over one project.
     *
     * @param scope                 the project; never null.
     * @param includeContradictions whether to run the (paid) LLM contradiction pass.
     * @param dryRun                {@code true} to preview without writing; {@code false} to persist a
     *                              {@code _lint/} page.
     * @return the findings (and where they were written, when not a dry run).
     */
    public LintReport lint(Scope scope, boolean includeContradictions, boolean dryRun) {
        if (scope == null) {
            throw new IllegalArgumentException("scope must not be null");
        }
        List<CuratorFinding> ruleFindings = curator.curate(scope).findings();
        List<Contradiction> contradictions = includeContradictions
                ? detector.detect(scope, knowledgePages(scope))
                : List.of();

        if (dryRun) {
            return new LintReport(
                    scope.workspaceSlug(), scope.projectSlug(), ruleFindings, contradictions, false, null);
        }

        String body = render(scope, ruleFindings, contradictions);
        Identity id = Identity.ofPage(scope.workspace(), scope.project(), PagePath.of(LINT_PATH));
        String commit = "memory_lint: " + scope.workspaceSlug() + "/" + scope.projectSlug();
        PageRecord written = pages.create(id, LINT_TITLE, body, wikiWriter.callbackFor(commit));
        links.syncPageLinks(written);
        return new LintReport(
                scope.workspaceSlug(), scope.projectSlug(), ruleFindings, contradictions, true, LINT_PATH);
    }

    /** Latest real knowledge pages (control {@code _}-prefixed pages excluded from the audit). */
    private List<PageRecord> knowledgePages(Scope scope) {
        return pages.listLatest(scope.workspace(), scope.project()).stream()
                .filter(p -> !p.page().path().value().startsWith("_"))
                .toList();
    }

    /** Render the findings as a markdown lint page, linking each flagged page with a wikilink. */
    private static String render(
            Scope scope, List<CuratorFinding> rules, List<Contradiction> contradictions) {
        StringBuilder sb = new StringBuilder(512);
        sb.append("# Lint report — ").append(scope.workspaceSlug()).append('/')
                .append(scope.projectSlug()).append("\n\n");
        sb.append("_Generated by memory_lint (rule-based curator")
                .append(contradictions.isEmpty() ? "" : " + LLM contradiction pass").append(")._\n\n");

        if (rules.isEmpty() && contradictions.isEmpty()) {
            sb.append("No issues found.\n");
            return sb.toString();
        }

        sb.append("## Rule findings (").append(rules.size()).append(")\n\n");
        if (rules.isEmpty()) {
            sb.append("_None._\n");
        } else {
            for (CuratorFinding f : rules) {
                sb.append("- **").append(f.rule()).append("** ").append(wikilink(f.path()))
                        .append(" — ").append(f.detail()).append('\n');
            }
        }

        sb.append("\n## Contradictions (").append(contradictions.size()).append(")\n\n");
        if (contradictions.isEmpty()) {
            sb.append("_None._\n");
        } else {
            for (Contradiction c : contradictions) {
                String refs = c.pages().stream().map(MemoryLintService::wikilink)
                        .reduce((a, b) -> a + " vs " + b).orElse("");
                sb.append("- ").append(refs).append(" — ").append(c.explanation()).append('\n');
            }
        }
        return sb.toString();
    }

    /** A same-project wikilink to a page path ({@code concepts/x.md} -> {@code [[concepts/x]]}). */
    private static String wikilink(String path) {
        String target = path.endsWith(".md") ? path.substring(0, path.length() - 3) : path;
        return "[[" + target + "]]";
    }
}
