/**
 * MCP transport (Streamable HTTP at /mcp) and the tool surface — read-only recall plus the issue #20
 * write tools (DD-003, ARCHITECTURE §2.2, §5.1).
 *
 * <h2>Issue #17 — MCP endpoint + read-only tools</h2>
 * {@link com.agentmemory.mcp.McpConfiguration} stands up the official MCP Java SDK's
 * Streamable-HTTP servlet transport at {@code /mcp} and an {@code McpSyncServer} bound to the five
 * read tools in {@link com.agentmemory.mcp.MemoryTools}: {@code memory_query} (hybrid recall over
 * {@link com.agentmemory.recall.RecallService}, #15/#16), {@code memory_recent} and
 * {@code memory_read_page} (over {@link com.agentmemory.store.PageRepository}, #12),
 * {@code memory_status} and {@code memory_briefing} (a structured snapshot with <em>no</em> LLM
 * call, over {@link com.agentmemory.mcp.McpReadRepository}). Handlers are thin: resolve the scope,
 * call one service, shape the JSON result.
 *
 * <p>Scope follows DD-003: {@link com.agentmemory.mcp.ScopeResolver} defaults to the most recently
 * active project (from hook capture) and accepts an explicit {@code workspace}+{@code project}
 * override. Each read tool advertises the read-only annotation hint.
 *
 * <h2>Issue #20 — memory_write_page + memory_delete_page (admission chain)</h2>
 * The two direct write tools in {@link com.agentmemory.mcp.MemoryWriteTools} let the user explicitly
 * remember a durable page or delete one. They are thin handlers over
 * {@link com.agentmemory.mcp.MemoryWriteService}, the admission chain that — with no special-case
 * bypass of versioning or the single-writer path (invariants #2/#3/#10) — privacy-redacts the body
 * ({@link com.agentmemory.hooks.Sanitizer}, #6), writes through the versioned store
 * ({@link com.agentmemory.store.PageRepository}, #12) and the wiki/git writer
 * ({@link com.agentmemory.wiki.WikiWriter}, #13), and records each mutation in {@code audit_log} with
 * the identity tuple + actor — all atomically. {@code memory_write_page} is immediately searchable
 * (the FTS column is generated by the insert); {@code memory_delete_page} is idempotent (deleting a
 * missing path is a no-op success) and advertises the destructive hint.
 *
 * <h2>Still scaffolding</h2>
 * Handoff/consolidate tools (#19/#22), LLM re-rank (#21) and {@code memory_explore} prose (#19)
 * arrive with their own issues; bearer auth is #38 (loopback default for now).
 */
package com.agentmemory.mcp;
