package com.agentmemory.autoimprove;

import com.agentmemory.core.Identity;
import com.agentmemory.core.PagePath;
import com.agentmemory.curate.CuratorFinding;
import com.agentmemory.curate.CuratorReport;
import com.agentmemory.curate.CuratorService;
import com.agentmemory.core.SessionId;
import com.agentmemory.recall.Scope;
import com.agentmemory.store.PageRecord;
import com.agentmemory.store.PageRepository;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The production {@link ProposalSource} (issue #30): adapts the #29 rule-based {@link CuratorService}
 * into a self-improvement proposal. Mirrors {@code memory_lint}'s consumption of the curator — it renders
 * the curator's findings into the canonical {@code _lint/report.md} page — but routes that write through
 * the auto-improve approval gate (and the optional eval gate) instead of writing directly, and runs it on
 * the scheduler's cadence.
 *
 * <p>The curator is <strong>scope-level</strong> and the LLM contradiction pass is intentionally omitted
 * (the auto-loop stays zero-cost and deterministic; the paid pass remains on-demand via {@code
 * memory_lint}). The proposal is therefore the rule-based lint report for the project. To avoid restaging
 * the same report each time the per-session scheduler reviews a session, the source is <strong>quiescent
 * when nothing changed</strong>: it emits a proposal only when the rendered report differs from the
 * project's current {@code _lint/report.md}.
 *
 * <p>Turning individual findings into corrective <em>actions</em> (forget a cold page, merge duplicates,
 * fix a dangling link) is a richer, action-shaped proposal model — a deliberate follow-up, not this wiring.
 */
public class CuratorProposalSource implements ProposalSource {

    /** The single canonical lint page per project (latest-versioned), shared with {@code memory_lint}. */
    static final String LINT_PATH = "_lint/report.md";

    private static final String LINT_TITLE = "Lint report";

    private static final Logger log = LoggerFactory.getLogger(CuratorProposalSource.class);

    private final CuratorService curator;
    private final PageRepository pages;

    public CuratorProposalSource(CuratorService curator, PageRepository pages) {
        this.curator = curator;
        this.pages = pages;
    }

    @Override
    public List<ProposedWrite> proposalsFor(Scope scope, SessionId session) {
        CuratorReport report = curator.curate(scope);
        if (report.isClean()) {
            return List.of(); // nothing flagged — nothing to propose
        }
        String body = render(scope, report);
        if (currentLintBodyEquals(scope, body)) {
            return List.of(); // unchanged since the last applied report — stay quiescent
        }
        log.debug("auto-improve: curator flagged {} finding(s) in {}/{}",
                report.total(), scope.workspaceSlug(), scope.projectSlug());
        return List.of(new ProposedWrite(
                LINT_PATH, LINT_TITLE, body, "page.edit",
                report.total() + " maintenance finding(s) from the rule-based curator"));
    }

    /** True when the project's current {@code _lint/report.md} already has exactly this body. */
    private boolean currentLintBodyEquals(Scope scope, String body) {
        Identity id = Identity.ofPage(scope.workspace(), scope.project(), PagePath.of(LINT_PATH));
        Optional<PageRecord> current = pages.readLatest(id);
        return current.isPresent() && current.get().page().body().equals(body);
    }

    /** Render the rule findings as a markdown report (mirrors {@code MemoryLintService}'s rule section). */
    private static String render(Scope scope, CuratorReport report) {
        StringBuilder sb = new StringBuilder(512);
        sb.append("# Lint report — ").append(scope.workspaceSlug()).append('/')
                .append(scope.projectSlug()).append("\n\n");
        sb.append("_Generated by auto-improve (rule-based curator)._\n\n");
        sb.append("## Rule findings (").append(report.total()).append(")\n\n");
        for (CuratorFinding f : report.findings()) {
            sb.append("- **").append(f.rule()).append("** ").append(wikilink(f.path()))
                    .append(" — ").append(f.detail()).append('\n');
        }
        return sb.toString();
    }

    /** A same-project wikilink to a page path ({@code concepts/x.md} -> {@code [[concepts/x]]}). */
    private static String wikilink(String path) {
        String target = path.endsWith(".md") ? path.substring(0, path.length() - 3) : path;
        return "[[" + target + "]]";
    }
}
